rustflags = [
  "-C", "link-arg=-fuse-ld=lld"
]

[profile.release]
opt-level = 1
debug = true
split-debuginfo = '...'  # Platform-specific.
strip = "none"
debug-assertions = false
overflow-checks = false
lto = false
panic = 'abort'
incremental = false
codegen-units = 16
rpath = false